language: node_js
node_js:
  - 12
services:
  - docker
before_script:
  - echo "No test to run"
script:
  - docker --version
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
  - docker tag udagram-api-feed jm247/udagram-api-feed:v1
  - docker tag udagram-api-user jm247/udagram-api-user:v1
  - docker tag udagram-frontend jm247/udagram-frontend:v1
  - docker tag udagram-reverseproxy jm247/udagram-reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jm247/udagram-api-feed:v1
  - docker push jm247/udagram-api-user:v1
  - docker push jm247/udagram-frontend:v1
  - docker push jm247/udagram-reverseproxy:v1
  
