version: '3'
services:
  reverseproxy:
    build: 
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy
  backend_user:
    build: ./udagram-api-user
    image: udagram-api-user
  backend_feed:
    build: ./udagram-api-feed
    image: udagram-api-feed
  frontend:
    build: ./udagram-frontend
    image: udagram-frontend:local